name: flutter_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  flutter_bloc: ^8.0.1
  cloud_firestore: ^5.2.1
  equatable: ^2.0.5
  firebase_core: ^3.3.0
  flutter_easyloading: ^3.0.5
  numberpicker: ^2.1.2
  dropdown_button2:  2.3.9
  firebase_auth: ^5.1.4
  http: ^1.2.2
  flutter_otp_text_field: ^1.1.3+2
  uuid: ^4.4.2
  crypto: ^3.0.5
  shared_preferences: ^2.0.15


flutter:
  assets:
    - assets/images/

  uses-material-design: true

